export const MOCK_SHUTTLES = [
    {
        "id": "5",
        "name": "Ambrotos",
        "serial_number": "AS-1498",
        "class": "Ammasarius-class multirole shuttle",
        "class_id": "2",
        "type": "Personnel Carrier",
        "capacity": "16",
        "base": "Bastion",
        "state": "Fully operational",
        "operable": "1",
        "status_name": "Ready",
        "status": "0",
        "assigned_to_name": null,
        "assigned_to_id": null,
        "required_skill": "Balance / Vliegbrevet",
        "required_skill_id": "31152"
    },
    {
        "id": "3",
        "name": "Mouse",
        "serial_number": "MS-558-50",
        "class": "AM-50 Razor interceptor",
        "class_id": "1",
        "type": "Scout",
        "capacity": "2",
        "base": "Bastion",
        "state": "Fully operational",
        "operable": "1",
        "status_name": "Ready",
        "status": "0",
        "assigned_to_name": null,
        "assigned_to_id": null,
        "required_skill": "Dynamic Entry",
        "required_skill_id": "31162"
    },
    {
        "id": "4",
        "name": "FireBird",
        "serial_number": "FH-001",
        "class": "Runner-Class",
        "class_id": "3",
        "type": "Fast Supply Carrier",
        "capacity": "2",
        "base": "Fennik",
        "state": "Fully operational",
        "operable": "1",
        "status_name": "On Mission",
        "status": "2",
        "assigned_to_name": "Sergei Konstantinova",
        "assigned_to_id": "99",
        "required_skill": "Balance / Vliegbrevet",
        "required_skill_id": "31152"
    },
    {
        "id": "1",
        "name": "Louisa",
        "serial_number": "LS-0032",
        "class": "Vespa-class multirole shuttle",
        "class_id": "4",
        "type": "Supply Carrier",
        "capacity": "8",
        "base": "Bastion",
        "state": "Fully operational",
        "operable": "1",
        "status_name": "On Mission",
        "status": "2",
        "assigned_to_name": null,
        "assigned_to_id": null,
        "required_skill": "Balance / Vliegbrevet",
        "required_skill_id": "31152"
    },
    {
        "id": "2",
        "name": "Najat",
        "serial_number": "NT-0427",
        "class": "Ammasarius-class multirole shuttle",
        "class_id": "2",
        "type": "Personnel Carrier",
        "capacity": "16",
        "base": "Bastion",
        "state": "Fully operational",
        "operable": "1",
        "status_name": "On Mission",
        "status": "2",
        "assigned_to_name": null,
        "assigned_to_id": null,
        "required_skill": "Balance / Vliegbrevet",
        "required_skill_id": "31152"
    },
    {
        "id": "6",
        "name": "Weasel",
        "serial_number": "WL-327-50",
        "class": "AM-50 Razor interceptor",
        "class_id": "1",
        "type": "Scout",
        "capacity": "2",
        "base": "Bastion",
        "state": "Fully operational",
        "operable": "1",
        "status_name": "On Mission",
        "status": "2",
        "assigned_to_name": null,
        "assigned_to_id": null,
        "required_skill": "Dynamic Entry",
        "required_skill_id": "31162"
    }
]